# Basic
title: Li Mei
subtitle: 个人技术博客
welcome_message: 主要是记录个人对技术的理解和开发过程中遇到的问题，欢迎了解更多。
description:  嗨，我是李梅，一名前端开发者。
creator: Li Mei

url: "https://limeii.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

tag_button:
    title: 标签
    description: 技术文章分类
    url: 'https://limeii.github.io/tag/'  

# Navigation buttons in the front page.
nav:
    #- {title: 简历, description: 我的简历, url: 'https://github.com/limeii'}
    - {title: Git, description: 个人代码, url: 'https://github.com/limeii'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: 
    # duoshuo: 
    
# Social
social:
    github: limeii
    mail: limei90s@foxmail.com

# Google Analytics
ga:
     id: UA-142143336-1
     host: auto
